
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres        
  password: FrankGuerrero   
  host: localhost 


development:
  <<: *default
  database: inventory_management_system_ro_r_development

test:
  <<: *default
  database: inventory_management_system_ro_r_test


production:
  <<: *default
  database: inventory_management_system_ro_r_production
  username: inventory_management_system_ro_r
  password: <%= ENV["INVENTORY_MANAGEMENT_SYSTEM_RO_R_DATABASE_PASSWORD"] %>
